#!/bin/csh

root -q -b exec_onefile.C\(\"$1\",\"$2\",true,false\)
root -q -b exec_onefile.C\(\"$1\",\"$2\",false,false\)
root -q -b exec_onefile.C\(\"$1\",\"$2\",true,true\)
root -q -b exec_onefile.C\(\"$1\",\"$2\",false,true\)

